version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.21

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v2-{{ checksum "go.sum" }}

      - run: go get -t -v ./...

      - save_cache:
          key: go-mod-v2-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/go/pkg/mod"

      - run: go test $(go list ./... | grep -v /examples/) -race
      - run: go test $(go list ./... | grep -v /examples/) -coverprofile=c_raw.out
      - run:
          name: Remove mock and generated code
          command: |
            cat c_raw.out | grep -v main > c.out

      # Run coverage report for Code Climate
      - run:
          name: Setup Code Climate test-reporter
          command: |
            mkdir -p tmp/
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
            ./tmp/cc-test-reporter before-build
      # Upload results
      - run:
          name: Upload coverage
          command: |
            ./tmp/cc-test-reporter after-build -t gocov --prefix github.com/nuts-foundation/go-leia/v4

